
services:
  request-react:
    container_name: request-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
